project:
  type: website

website:
  title: "Stage4 EAA NEXRAD"
  navbar:
    left:
      - text: "24-Hour"
        href: recent-24.qmd
      - text: "YTD"
        href: year-to-date.qmd
      - text: "Hyetograph"
        href: hyet.qmd

format:
  html:
    page-layout: full
    css: [styles.css, styles-override.css]
    toc: false
